services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .next:/app/.next
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm i && npm run dev"
    networks:
      - shared-network

volumes:
  node_modules:
  next_build:

networks:
 shared-network: 
  external: true

