services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    environment:
      - PORT=4000
    command: npm run dev
